task default: ['dym.so']

file "Makefile" do
  `ruby extconf.rb`
end

file 'dym.so' => ['Makefile', 'dym.c'] do
  `make`
end

task :clean do
  rm_f 'dym.o'
  rm_f 'dym.so'
  rm_f 'mkmf.log'
  rm_f 'Makefile'
end
